Add models testing
MoyasiGinko/Rails-Blog pull request #4
Opened 2023-08-26 22:22 UTC by MoyasiGinko

### In this milestone:
- Created a new branch
- Added rspec gem
- Implemented Test directory
- Added test files for all models

2023-08-26 22:56 UTC, Whoistolu requested changes
Hi @MoyasiGinko 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [x]  _Check the inline comments under the review for sections to improve._
- [x] [REQUIRED] For the `Post` model, kindly add validation that will indicate the CommentsCounter as an integer, then it must be greater than or equal to zero.
- [x] [REQUIRED] Also, for the `Post` model, kindly add validations that will indicate the  LikesCounter must be an integer greater than or equal to zero.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

### N/A

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 22:56 UTC, Whoistolu commented on app/models/post.rb
> +  validates :title, presence: true, length: { maximum: 100 }
- [ ] [REQUIRED] Great job validating the `Post` model, however, the Project requirement states that 
title must not exceed 250 characters. Kindly resolve this as you are validating against 100 characters at the moment.

2023-08-27 04:29 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi @MoyasiGinko 

Good job implementing the suggested changes💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Models are validated
-  ✅ Validation specs are added
-  ✅ All tests are passing
-  ✅ Linters are working properly

## Optional suggestions ❕
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-27 04:29 UTC, KanzaTahreem commented on spec/models/post_spec.rb
- [OPTIONAL] Good job for adding the validations for `comments_counter` and `likes_counter` as suggested 👏 I believe it would be beneficial to include tests for these validations. Since the previous reviewer didn't ask for testing these validations after their addition, I am making it optional. However, I highly recommend addressing this concern ✨📌

2023-08-27 04:31 UTC, MoyasiGinko commented on spec/models/post_spec.rb
Thank you @KanzaTahreem for suggesting that I will keep that in mind. Have a great day 😄

2023-08-27 04:31 UTC, merged